version: "3.8"

services:
  batch-rag:
    build: .
    container_name: batch_rag_app
    ports:
      - "8501:8501"
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    network_mode: bridge
